# Generated by Django 4.2.15 on 2024-09-08 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_usermobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermobile',
            name='user_status',
            field=models.IntegerField(default=0),
        ),
    ]
