# Generated by Django 4.2.15 on 2024-09-15 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_user_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payroll',
            old_name='bonuses',
            new_name='pf',
        ),
    ]
