# Generated by Django 4.2.15 on 2024-09-19 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_compensativeleaveapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=100)),
                ('friend_name', models.CharField(max_length=100)),
                ('friend_mobile', models.CharField(max_length=10)),
                ('message', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='usermobile',
            name='mobile_no',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
