# Generated by Django 4.2.15 on 2024-09-19 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_friendmessage_alter_user_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendmessage',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apps.user'),
            preserve_default=False,
        ),
    ]
