# Generated by Django 4.2.15 on 2024-09-19 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_friendmessage_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FriendMessage',
            new_name='Refer_friends',
        ),
    ]
